### Auth -> Register
POST http://localhost:3000/auth/register 
Content-Type: application/json

{
    "username": "lctuan.08072",
    "email": "lctuan.08072@gmail.com",
    "password": "@@@Abc123"
}

### Auth -> Login
POST http://localhost:3000/auth/login 
Content-Type: application/json

{
    "username": "lctuan.0807",
    "password": "@@@Abc123"
}


### Auth -> Me
GET http://localhost:3000/auth/me
# Authorization: Bearer xxx
