### User -> Register
POST http://localhost:3000/auth/register 
Content-Type: application/json

{
    "username": "lctuan.0807",
    "email": "lctuan.0807@gmail.com",
    "password": "@@@Abc123"
}

### User -> Login
POST http://localhost:3000/auth/login 
Content-Type: application/json

{
    "username": "lctuan.0807",
    "password": "@@@Abc123"
}

