### Auth -> Register
POST http://localhost:3000/auth/register 
Content-Type: application/json

{
    "username": "lctuan.0807-4",
    "email": "lctuan.0807-4@gmail.com",
    "password": "@@@Abc123"
}

### Auth -> Login
POST http://localhost:3000/auth/login 
Content-Type: application/json

{
    "username": "lctuan.0807",
    "password": "@@@Abc123"
}


### Auth -> Me
GET http://localhost:3000/auth/me
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImxjdHVhbi4wODA3Iiwic3ViIjoxLCJpYXQiOjE3ODI1NDg1MDMsImV4cCI6MTc4MjYzNDkwM30.Sq8ZOePGHslEnX1LK72vDnEmKN7McnjUjp_RNXkUjq8
